export const convertMouseButton = (btn: number): number | undefined => {
  switch (btn) {
    case 0: return 1; // Left
    case 1: return 3; // Middle
    case 2: return 2; // Right
    default: return undefined;
  }
};

export const convertMouseButtons = (btn: number): number | undefined => {
  if ((btn & 1) !== 0) return 1; // Left
  if ((btn & 2) !== 0) return 2; // Right
  if ((btn & 4) !== 0) return 3; // Middle
  return undefined;
};

const enum EKeyCode {
  One = 0, Two, Three, Four, Five, Six, Seven, Eight, Nine, Zero,
  Minus,
  Equals,
  Backspace,
  Tab,
  A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
  LeftBracket,
  RightBracket,
  Enter,
  LeftCtrl,
  SemiColon,
  Apostrophe,
  Grave,
  LeftShift,
  Backslash,
  Comma,
  Period,
  Slash,
  RightShift,
  Multiply,
  LeftAlt,
  Space,
  CapsLock,
  F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15,
  NumLock,
  ScrollLock,
  NumPad0, NumPad1, NumPad2, NumPad3, NumPad4, NumPad5, NumPad6, NumPad7, NumPad8, NumPad9,
  NumPadSubtract,
  NumPadAdd,
  NumPadDecimal,
  Kana,
  Convert,
  Noconvert,
  Yen,
  NumPadEquals,
  Circumflex,
  At,
  Colon,
  Underscore,
  Kanji,
  Stop,
  Ax,
  NumPadEnter,
  RightCtrl,
  NumPadComma,
  NumPadDivide,
  RightAlt,
  Pause,
  Home,
  Up,
  PageUp,
  Left,
  Right,
  End,
  Down,
  PageDown,
  Insert,
  Delete,
}

export type KeyCode = EKeyCode | { __keycodeBrand: never }

/**
 * Mapping of KeyboardEvent.code and KeyboardEvent.key
 *
 * @see https://www.w3.org/TR/uievents-key/
 * @see https://www.w3.org/TR/uievents-code/
 */
const keyboardCodes: { [key: string]: EKeyCode } = {
  "Digit1": EKeyCode.One, "1": EKeyCode.One,
  "Digit2": EKeyCode.Two, "2": EKeyCode.Two,
  "Digit3": EKeyCode.Three, "3": EKeyCode.Three,
  "Digit4": EKeyCode.Four, "4": EKeyCode.Four,
  "Digit5": EKeyCode.Five, "5": EKeyCode.Five,
  "Digit6": EKeyCode.Six, "6": EKeyCode.Six,
  "Digit7": EKeyCode.Seven, "7": EKeyCode.Seven,
  "Digit8": EKeyCode.Eight, "8": EKeyCode.Eight,
  "Digit9": EKeyCode.Nine, "9": EKeyCode.Nine,
  "Digit0": EKeyCode.Zero, "0": EKeyCode.Zero,
  "Minus": EKeyCode.Minus, "-": EKeyCode.Minus,
  "Equal": EKeyCode.Equals,
  "Backspace": EKeyCode.Backspace,
  "Tab": EKeyCode.Tab,
  "KeyQ": EKeyCode.Q, "Q": EKeyCode.Q,
  "KeyW": EKeyCode.W, "W": EKeyCode.W,
  "KeyE": EKeyCode.E, "E": EKeyCode.E,
  "KeyR": EKeyCode.R, "R": EKeyCode.R,
  "KeyT": EKeyCode.T, "T": EKeyCode.T,
  "KeyY": EKeyCode.Y, "Y": EKeyCode.Y,
  "KeyU": EKeyCode.U, "U": EKeyCode.U,
  "KeyI": EKeyCode.I, "I": EKeyCode.I,
  "KeyO": EKeyCode.O, "O": EKeyCode.O,
  "KeyP": EKeyCode.P, "P": EKeyCode.P,
  "BracketLeft": EKeyCode.LeftBracket, "(": EKeyCode.LeftBracket,
  "BracketRight": EKeyCode.RightBracket, ")": EKeyCode.RightBracket,
  "Enter": EKeyCode.Enter,
  "ControlLeft": EKeyCode.LeftCtrl, "Control": EKeyCode.LeftCtrl,
  "KeyA": EKeyCode.A, "A": EKeyCode.A,
  "KeyS": EKeyCode.S, "S": EKeyCode.S,
  "KeyD": EKeyCode.D, "D": EKeyCode.D,
  "KeyF": EKeyCode.F, "F": EKeyCode.F,
  "KeyG": EKeyCode.G, "G": EKeyCode.G,
  "KeyH": EKeyCode.H, "H": EKeyCode.H,
  "KeyJ": EKeyCode.J, "J": EKeyCode.J,
  "KeyK": EKeyCode.K, "K": EKeyCode.K,
  "KeyL": EKeyCode.L, "L": EKeyCode.L,
  "Semicolon": EKeyCode.SemiColon, ";": EKeyCode.SemiColon,
  "Quote": EKeyCode.Apostrophe, "'": EKeyCode.Apostrophe,
  "Backquote": EKeyCode.Grave, "`": EKeyCode.Grave,
  "ShiftLeft": EKeyCode.LeftShift, "Shift": EKeyCode.LeftShift,
  "IntlBackslash": EKeyCode.Backslash,
  "KeyZ": EKeyCode.Z, "Z": EKeyCode.Z,
  "KeyX": EKeyCode.X, "X": EKeyCode.X,
  "KeyC": EKeyCode.C, "C": EKeyCode.C,
  "KeyV": EKeyCode.V, "V": EKeyCode.V,
  "KeyB": EKeyCode.B, "B": EKeyCode.B,
  "KeyN": EKeyCode.N, "N": EKeyCode.N,
  "KeyM": EKeyCode.M, "M": EKeyCode.M,
  "Comma": EKeyCode.Comma, ",": EKeyCode.Comma,
  "Period": EKeyCode.Period, ".": EKeyCode.Period,
  "Slash": EKeyCode.Slash, "/": EKeyCode.Slash,
  "ShiftRight": EKeyCode.RightShift,
  "NumpadMultiply": EKeyCode.Multiply,
  "AltLeft": EKeyCode.LeftAlt, "Alt": EKeyCode.LeftAlt,
  "Space": EKeyCode.Space, " ": EKeyCode.Space,
  "CapsLock": EKeyCode.CapsLock,
  "F1": EKeyCode.F1,
  "F2": EKeyCode.F2,
  "F3": EKeyCode.F3,
  "F4": EKeyCode.F4,
  "F5": EKeyCode.F5,
  "F6": EKeyCode.F6,
  "F7": EKeyCode.F7,
  "F8": EKeyCode.F8,
  "F9": EKeyCode.F9,
  "F10": EKeyCode.F10,
  "NumLock": EKeyCode.NumLock,
  "ScollLock": EKeyCode.ScrollLock,
  "Numpad7": EKeyCode.NumPad7,
  "Numpad8": EKeyCode.NumPad8,
  "Numpad9": EKeyCode.NumPad9,
  "NumpadSubtract": EKeyCode.NumPadSubtract,
  "Numpad4": EKeyCode.NumPad4,
  "Numpad5": EKeyCode.NumPad5,
  "Numpad6": EKeyCode.NumPad6,
  "NumpadAdd": EKeyCode.NumPadAdd,
  "Numpad1": EKeyCode.NumPad1,
  "Numpad2": EKeyCode.NumPad2,
  "Numpad3": EKeyCode.NumPad3,
  "Numpad0": EKeyCode.NumPad0,
  "NumpadDecimal": EKeyCode.NumPadDecimal,
  "F11": EKeyCode.F11,
  "F12": EKeyCode.F12,
  "F13": EKeyCode.F13,
  "F14": EKeyCode.F14,
  "F15": EKeyCode.F15,

  // I have absolutely no clue about these. If someone has a keyboard with these
  // on, please confim that they're right.
  "KanaMode": EKeyCode.Kana,
  "Convert": EKeyCode.Convert,
  "NonConvert": EKeyCode.Noconvert,
  "IntlYen": EKeyCode.Yen,
  "NumpadEqual": EKeyCode.NumPadEquals,
  "Cirmcumflex": EKeyCode.Circumflex,
  "At": EKeyCode.At,
  "Colon": EKeyCode.Colon,
  "Underscore": EKeyCode.Underscore,
  "Kanji": EKeyCode.Kanji,
  "Stop": EKeyCode.Stop,
  "Ax": EKeyCode.Ax,

  "NumpadEnter": EKeyCode.Enter, // We just map to "enter" right now, as that's what LJWGL 2 does. Not sure about 3.
  "ControlRight": EKeyCode.RightCtrl,
  "NumpadComma": EKeyCode.NumPadComma,
  "NumpadDivide": EKeyCode.NumPadDivide,
  "AltRight": EKeyCode.RightAlt,
  "Pause": EKeyCode.Pause,
  "Home": EKeyCode.Home,
  "ArrowUp": EKeyCode.Up,
  "PageUp": EKeyCode.PageUp,
  "ArrowLeft": EKeyCode.Left,
  "ArrowRight": EKeyCode.Right,
  "End": EKeyCode.End,
  "ArrowDown": EKeyCode.Down,
  "PageDown": EKeyCode.PageDown,
  "Insert": EKeyCode.Insert,
  "Delete": EKeyCode.Delete,
};

export const convertKey = (key: string): KeyCode | undefined => keyboardCodes[key];

const names = [
  "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "zero",
  "minus",
  "equals",
  "backspace",
  "tab",
  "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
  "leftBracket",
  "rightBracket",
  "enter",
  "leftCtrl",
  "semiColon",
  "apostrophe",
  "grave",
  "leftShift",
  "backslash",
  "comma",
  "period",
  "slash",
  "rightShift",
  "multiply",
  "leftAlt",
  "space",
  "capsLock",
  "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12", "f13", "f14", "f15",
  "numLock",
  "scrollLock",
  "numPad0", "numPad1", "numPad2", "numPad3", "numPad4", "numPad5", "numPad6", "numPad7", "numPad8", "numPad9",
  "numPadSubtract",
  "numPadAdd",
  "numPadDecimal",
  "kana",
  "convert",
  "noconvert",
  "yen",
  "numPadEquals",
  "circumflex",
  "at",
  "colon",
  "underscore",
  "kanji",
  "stop",
  "ax",
  "numPadEnter",
  "rightCtrl",
  "numPadComma",
  "numPadDivide",
  "rightAlt",
  "pause",
  "home",
  "up",
  "pageUp",
  "left",
  "right",
  "end",
  "down",
  "pageDown",
  "insert",
  "delete",
];

export const keyName = (key: KeyCode): string => names[key as EKeyCode];

const lwjgl2Codes = [
  2 /* one */, 3 /* two */, 4 /* three */, 5 /* four */, 6 /* five */, 7 /* six */, 8 /* seven */, 9 /* eight */, 10 /* nine */, 11 /* zero */,
  12 /* minus */,
  13 /* equals */,
  14 /* backspace */,
  15 /* tab */,
  30 /* a */, 48 /* b */, 46 /* c */, 32 /* d */, 18 /* e */, 33 /* f */, 34 /* g */, 35 /* h */, 23 /* i */, 36 /* j */, 37 /* k */, 38 /* l */, 50 /* m */, 49 /* n */, 24 /* o */, 25 /* p */, 16 /* q */, 19 /* r */, 31 /* s */, 20 /* t */, 22 /* u */, 47 /* v */, 17 /* w */, 45 /* x */, 21 /* y */, 44 /* z */,
  26 /* leftBracket */,
  27 /* rightBracket */,
  28 /* enter */,
  29 /* leftCtrl */,
  39 /* semiColon */,
  40 /* apostrophe */,
  41 /* grave */,
  42 /* leftShift */,
  43 /* backslash */,
  51 /* comma */,
  52 /* period */,
  53 /* slash */,
  54 /* rightShift */,
  55 /* multiply */,
  56 /* leftAlt */,
  57 /* space */,
  58 /* capsLock */,
  59 /* f1 */, 60 /* f2 */, 61 /* f3 */, 62 /* f4 */, 63 /* f5 */, 64 /* f6 */, 65 /* f7 */, 66 /* f8 */, 67 /* f9 */, 68 /* f10 */, 87 /* f11 */, 88 /* f12 */, 100 /* f13 */, 101 /* f14 */, 102 /* f15 */,
  69 /* numLock */,
  70 /* scrollLock */,
  82 /* numPad0 */, 79 /* numPad1 */, 80 /* numPad2 */, 81 /* numPad3 */, 75 /* numPad4 */, 76 /* numPad5 */, 77 /* numPad6 */, 71 /* numPad7 */, 72 /* numPad8 */, 73 /* numPad9 */,
  74 /* numPadSubtract */,
  78 /* numPadAdd */,
  83 /* numPadDecimal */,
  112 /* kana */,
  121 /* convert */,
  123 /* noconvert */,
  125 /* yen */,
  141 /* numPadEquals */,
  144 /* circumflex */,
  145 /* at */,
  146 /* colon */,
  147 /* underscore */,
  148 /* kanji */,
  149 /* stop */,
  150 /* ax */,
  156 /* numPadEnter */,
  157 /* rightCtrl */,
  179 /* numPadComma */,
  181 /* numPadDivide */,
  184 /* rightAlt */,
  197 /* pause */,
  199 /* home */,
  200 /* up */,
  201 /* pageUp */,
  203 /* left */,
  205 /* right */,
  207 /* end */,
  208 /* down */,
  209 /* pageDown */,
  210 /* insert */,
  211 /* delete */,
];

export const lwjgl2Code = (key: KeyCode): number | undefined => lwjgl2Codes[key as EKeyCode];

const lwjgl3Codes = [
  49 /* one */, 50 /* two */, 51 /* three */, 52 /* four */, 53 /* five */, 54 /* six */, 55 /* seven */, 56 /* eight */, 57 /* nine */, 48 /* zero */,
  45 /* minus */,
  61 /* equals */,
  259 /* backspace */,
  258 /* tab */,
  65 /* a */, 66 /* b */, 67 /* c */, 68 /* d */, 69 /* e */, 70 /* f */, 71 /* g */, 72 /* h */, 73 /* i */, 74 /* j */, 75 /* k */, 76 /* l */, 77 /* m */, 78 /* n */, 79 /* o */, 80 /* p */, 81 /* q */, 82 /* r */, 83 /* s */, 84 /* t */, 85 /* u */, 86 /* v */, 87 /* w */, 88 /* x */, 89 /* y */, 90 /* z */,
  91 /* leftBracket */,
  93 /* rightBracket */,
  257 /* enter */,
  341 /* leftCtrl */,
  -1 /* semiColon */,
  39 /* apostrophe */,
  96 /* grave */,
  340 /* leftShift */,
  92 /* backslash */,
  44 /* comma */,
  46 /* period */,
  47 /* slash */,
  344 /* rightShift */,
  -1 /* multiply */,
  342 /* leftAlt */,
  32 /* space */,
  280 /* capsLock */,
  290 /* f1 */, 291 /* f2 */, 292 /* f3 */, 293 /* f4 */, 294 /* f5 */, 295 /* f6 */, 296 /* f7 */, 297 /* f8 */, 298 /* f9 */, 299 /* f10 */, 300 /* f11 */, 301 /* f12 */, 302 /* f13 */, 303 /* f14 */, 304 /* f15 */,
  282 /* numLock */,
  281 /* scrollLock */,
  320 /* numPad0 */, 321 /* numPad1 */, 322 /* numPad2 */, 323 /* numPad3 */, 324 /* numPad4 */, 325 /* numPad5 */, 326 /* numPad6 */, 327 /* numPad7 */, 328 /* numPad8 */, 329 /* numPad9 */,
  333 /* numPadSubtract */,
  334 /* numPadAdd */,
  330 /* numPadDecimal */,
  -1 /* kana */,
  -1 /* convert */,
  -1 /* noconvert */,
  -1 /* yen */,
  -1 /* numPadEquals */,
  -1 /* circumflex */,
  -1 /* at */,
  -1 /* colon */,
  -1 /* underscore */,
  -1 /* kanji */,
  -1 /* stop */,
  -1 /* ax */,
  335 /* numPadEnter */,
  345 /* rightCtrl */,
  -1 /* numPadComma */,
  331 /* numPadDivide */,
  346 /* rightAlt */,
  284 /* pause */,
  268 /* home */,
  265 /* up */,
  266 /* pageUp */,
  263 /* left */,
  262 /* right */,
  269 /* end */,
  264 /* down */,
  267 /* pageDown */,
  260 /* insert */,
  261 /* delete */,
];

export const lwjgl3Code = (key: KeyCode): number | undefined => {
  const result = lwjgl3Codes[key as EKeyCode];
  return result < 0 ? undefined : result;
};
